---
- name: create tmp file to test ansible
  hosts: all
  tasks:
    - name: create test file
      file:
        path: /home/livefacter/testfile
        state: touch
        mode: u=rw

    - name: get stat of tmp file
      file:
        path: /home/livefacter/testfile
        state: file
      register: tmpfile

    - debug:
        var: tmpfile
